=== blessed-me/PersonalProject/xmlproject/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>

<xs:element name="customerdata">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="customer" minOccurs="1" maxOccurs="1" />
				
			</xs:sequence>
			
		</xs:complexType>
	</xs:element>

<xs:element name="customer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="first-name" minOccurs="1" maxOccurs="1" />
				<xs:element ref="last-name" minOccurs="1" maxOccurs="1" />
				<xs:element ref="contactinfo" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="customerid" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="first-name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="last-name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="contactinfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="residence" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="residence">
		<xs:complexType>
			<xs:sequence> <!-- choice, All -->
				<xs:element ref="address" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="phone" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="address">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== blessed-me/PersonalProject/xmlproject/NewFile4.xml
<?xml version="1.0" encoding="UTF-8"?>
<customerdata xsi:noNamespaceSchemaLocation="NewXMLSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<customer customerid="abc">
	<first-name>vipin</first-name>
	<last-name>sahu</last-name>
	<contactinfo>
		<residence>
			<address>302 e</address>
			<phone>8989898</phone>
		</residence>
	</contactinfo>
</customer>

</customerdata>
